create table tb_worker (id int8 generated by default as identity, daily_income float8, name varchar(255), primary key (id));
insert into tb_worker (name, daily_income) values ('Bob', 200.0);
insert into tb_worker (name, daily_income) values ('Maria', 300.0);
insert into tb_worker (name, daily_income) values ('Alex', 250.0);
