spring.application.name=hr-config-server
server.port=8888

# Configuração do repositório Git para o Config Server
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.uri=https://github.com/guilhermepagio/curso-udemy-microsservicos-java-com-spring-boot-e-spring-cloud.git
spring.cloud.config.server.git.search-paths=hr-config-server/configs